export const defaultContent = {
  hero: {
    badge: "Est. 2023",
    line1: "Premium",
    line2: "Detailing.",
    line3_1: "Pristine",
    line3_2: "Results.",
    tagline: "We take pride in every detail. Professional auto detailing bringing the showroom shine straight to you.",
    btn1: "Book Now",
    btn2: "View Services",
    btn3: "Contact Us",
  },
  about: {
    eyebrow: "About Us",
    heading: "Obsessed with Perfection",
    p1: "At Albert Auto Detailing, we specialize in premium car detailing services designed to keep your vehicle looking clean, fresh, and protected.",
    p2: "Since 2023, we have focused on quality, attention to detail, and customer satisfaction. Every vehicle is treated with the utmost care because we understand that your car is an investment. We take pride in every detail, delivering results that speak for themselves.",
    stat1Value: "100%",
    stat1Label: "Satisfaction",
    stat2Value: "Premium",
    stat2Label: "Products Used",
  },
  services: {
    eyebrow: "Our Services",
    heading: "Expert Auto Care",
    items: [
      { title: "VIP Interior Clean", description: "Deep clean for a luxurious interior experience. We address every crevice, treating leather, plastics, and fabrics.", active: true },
      { title: "2 Step Wax", description: "Enhances shine and protects your paint from harsh elements while giving a wet, mirror-like finish.", active: true },
      { title: "Shampoo", description: "Thorough hand wash to remove dirt and grime, ensuring a scratch-free pristine exterior.", active: true },
      { title: "Bumper to Bumper", description: "Complete detailing inside and out. The ultimate package for a total vehicle reset.", active: true },
      { title: "Headlight Restoration", description: "Restores clarity and improves night visibility, removing yellowing and oxidation from lenses.", active: true },
      { title: "Wax & Protect", description: "Long-lasting protection with a brilliant shine that repels water and environmental contaminants.", active: true },
    ],
  },
  mobileService: {
    heading1: "Mobile Service",
    heading2: "Available",
    body: "We come to you! Enjoy professional auto detailing at your home, workplace, or preferred location. We bring our own premium supplies and equipment.",
    cta: "Schedule Mobile Service",
  },
  whyUs: {
    eyebrow: "Why Choose Us",
    heading: "Driven by Quality",
    body: "We don't just wash cars; we restore and protect them. Our rigorous standards ensure every vehicle leaving our care looks better than the day it left the showroom.",
    cta: "Get an estimate",
    benefits: [
      "Premium detailing services",
      "Attention to every detail",
      "Mobile service available",
      "Professional results",
      "Interior and exterior care",
      "Quality products",
      "Customer satisfaction focused",
    ],
  },
  gallery: {
    eyebrow: "Our Work",
    heading: "See The Difference",
    body: "Our results speak for themselves. Browse through some of our recent premium auto detailing projects.",
  },
  contact: {
    eyebrow: "Get In Touch",
    heading: "Book Your Appointment",
    body: "Ready to give your vehicle the premium treatment it deserves? Contact us today to schedule your auto detailing service.",
    phone: "475-689-8301",
    email: "albertautodetailing2094@gmail.com",
    instagram: "albert_auto_detailing",
    whatsapp: "",
    facebook: "",
    tiktok: "",
    address: "",
    hours: "",
    whatsappText: "Hi! I'd like to book a detailing service.",
    callLabel: "Call Now",
    emailLabel: "Send Email",
    instagramLabel: "Follow Us",
  },
  footer: {
    tagline: "Premium Detailing. Pristine Results.",
    sub: "We take pride in every detail.",
    rights: "All rights reserved.",
  },
  sections: {
    hero: true,
    about: true,
    services: true,
    mobileService: true,
    whyUs: true,
    gallery: true,
    contact: true,
  },
};

export type SiteContent = typeof defaultContent;
