export const defaultContent = {
  hero: {
    badge: "Est. 2023 · Norwalk, CT",
    line1: "Premium",
    line2: "Detailing.",
    line3_1: "Expert",
    line3_2: "Results.",
    tagline: "Professional detailing that restores your vehicle to a like-new shine and protection.",
    btn1: "Get a Free Quote",
    btn2: "Our Services",
    btn3: "WhatsApp Us",
  },
  about: {
    eyebrow: "About Us",
    heading: "Obsessed with Perfection",
    p1: "At Albert Auto Detailing, we specialize in premium car detailing services designed to keep your vehicle looking clean, fresh, and protected — serving Norwalk, CT and surrounding areas.",
    p2: "Since 2023, we have focused on quality, attention to detail, and customer satisfaction. Every vehicle is treated with the utmost care because we understand that your car is an investment. We take pride in every detail, delivering results that speak for themselves.",
    stat1Value: "100%",
    stat1Label: "Satisfaction",
    stat2Value: "5★",
    stat2Label: "Rated Service",
  },
  services: {
    eyebrow: "Our Services",
    heading: "Expert Auto Care",
    items: [
      { title: "Interior & Exterior Wash", description: "Complete interior and exterior cleaning to remove dirt, grime, and buildup for a spotless finish inside and out.", active: true },
      { title: "Paint Correction", description: "Remove swirl marks, scratches, and oxidation to restore your paint to a mirror-like, showroom-quality finish.", active: true },
      { title: "Ceramic Coating", description: "Long-lasting nano-ceramic protection that repels water, UV rays, and contaminants for years of pristine shine.", active: true },
      { title: "Headlight Restoration", description: "Restores clarity and improves night visibility, removing yellowing and oxidation from lenses.", active: true },
      { title: "Engine Cleaning", description: "Thorough engine bay degreasing and cleaning for a pristine engine that performs and looks its best.", active: true },
      { title: "Leather Protection", description: "Deep conditioning and protection treatment that restores suppleness, color, and durability to leather surfaces.", active: true },
      { title: "Stain Removal", description: "Advanced treatment to eliminate tough stains from upholstery, carpets, and surfaces — results guaranteed.", active: true },
    ],
  },
  promotions: {
    eyebrow: "Limited Time Offers",
    heading: "Special Promotions",
    items: [
      { text: "20% off your first service", active: true },
      { text: "$15 off any full detailing package", active: true },
      { text: "Free interior wash on your first visit", active: true },
      { text: "Free consultation — no obligation", active: true },
    ],
  },
  mobileService: {
    heading1: "Mobile Service",
    heading2: "Available",
    body: "We come to you! Enjoy professional auto detailing at your home, workplace, or preferred location. We bring our own premium supplies and equipment.",
    cta: "Schedule Mobile Service",
  },
  whyUs: {
    eyebrow: "Why Choose Us",
    heading: "Driven by Quality",
    body: "We don't just wash cars; we restore and protect them. Our rigorous standards ensure every vehicle leaving our care looks better than the day it left the showroom.",
    cta: "Get an estimate",
    benefits: [
      "Premium detailing services",
      "Attention to every detail",
      "Mobile service available",
      "Professional results",
      "Interior and exterior care",
      "Quality products used",
      "Customer satisfaction focused",
    ],
  },
  gallery: {
    eyebrow: "Our Work",
    heading: "Before & After",
    body: "Our results speak for themselves. Browse through some of our recent premium auto detailing projects.",
  },
  testimonials: [
    { name: "Carlos M.", comment: "Absolutely incredible service! My car looks brand new after the ceramic coating. Albert and his team are true professionals.", active: true },
    { name: "Maria G.", comment: "Best detailing in Norwalk! They restored my headlights and did a full interior clean. I couldn't be happier with the results.", active: true },
    { name: "John D.", comment: "The paint correction on my BMW was flawless. These guys know what they're doing. Highly recommend Albert Auto Detailing!", active: true },
  ],
  faq: {
    eyebrow: "FAQ",
    heading: "Got Questions?",
    items: [
      { q: "How long does a full detail take?", a: "A complete interior and exterior detail typically takes 3–5 hours depending on vehicle size and condition." },
      { q: "Do you offer mobile service?", a: "Yes! We come to your home, workplace, or any preferred location in the Norwalk, CT area. Just share your address when booking." },
      { q: "How much does detailing cost?", a: "We provide personalized quotes based on your vehicle and services needed. Contact us for a free, no-obligation estimate." },
      { q: "How often should I get my car detailed?", a: "We recommend a full detail every 4–6 months and a maintenance wash monthly to keep your vehicle in top condition." },
      { q: "What products do you use?", a: "We use only professional-grade, premium products that are safe for your vehicle's paint, interior, and surfaces." },
      { q: "Do you offer ceramic coating?", a: "Yes! Our ceramic coating provides long-lasting protection. We can recommend the best package for your vehicle." },
    ],
  },
  contact: {
    eyebrow: "Get In Touch",
    heading: "Book Your Appointment",
    body: "Ready to give your vehicle the premium treatment it deserves? Contact us today to schedule your detailing service.",
    phone: "475-689-8301",
    email: "albertautodetailing2024@gmail.com",
    instagram: "albert_auto_detailing",
    whatsapp: "14756898301",
    facebook: "",
    tiktok: "",
    address: "Norwalk, Connecticut 06851",
    hours: "Mon–Sat: 8am–6pm",
    whatsappText: "Hi! I'd like to book a detailing service.",
    callLabel: "Call Now",
    emailLabel: "Send Email",
    instagramLabel: "Follow Us",
  },
  quoteForm: {
    eyebrow: "Request a Quote",
    heading: "Get Your Free Estimate",
    body: "Fill out the form and we'll get back to you with a personalized quote. No obligation, completely free.",
    submitLabel: "Send Request via WhatsApp",
  },
  location: {
    eyebrow: "Find Us",
    heading: "Our Location",
    address: "Norwalk, Connecticut 06851",
    hours: "Mon–Sat: 8am–6pm",
    areaNote: "We also offer mobile service throughout Norwalk, Stamford, Bridgeport, and surrounding CT areas.",
  },
  footer: {
    tagline: "Premium Detailing. Pristine Results.",
    sub: "Serving Norwalk, CT and surrounding areas.",
    rights: "All rights reserved.",
  },
  sections: {
    hero: true,
    about: true,
    services: true,
    promotions: true,
    mobileService: true,
    whyUs: true,
    gallery: true,
    testimonials: true,
    faq: true,
    contact: true,
    quoteForm: true,
    location: true,
  },
};

export type SiteContent = typeof defaultContent;
