export const defaultContent = {
  hero: {
    badge: "Est. 2023 · Norwalk, CT",
    line1: "Precision",
    line2: "Detailing.",
    line3_1: "Perfected.",
    line3_2: "",
    tagline: "Professional detailing that restores your vehicle to a like-new shine and protection.",
    btn1: "Get a Free Quote",
    btn2: "Our Services",
    btn3: "WhatsApp Us",
  },
  about: {
    eyebrow: "About Us",
    heading: "Obsessed with Perfection",
    p1: "At Albert Auto Detailing, we specialize in premium car detailing services designed to keep your vehicle looking clean, fresh, and protected — serving Norwalk, CT and surrounding areas.",
    p2: "Since 2023, we have focused on quality, attention to detail, and customer satisfaction. Every vehicle is treated with the utmost care because we understand that your car is an investment. We take pride in every detail, delivering results that speak for themselves.",
    stat1Value: "100%",
    stat1Label: "Satisfaction",
    stat2Value: "5★",
    stat2Label: "Rated Service",
  },
  services: {
    eyebrow: "Our Services",
    heading: "Expert Auto Care",
    items: [
      { title: "Interior & Exterior Wash", description: "Complete interior and exterior cleaning to remove dirt, grime, and buildup for a spotless finish inside and out.", active: true },
      { title: "Paint Correction", description: "Remove swirl marks, scratches, and oxidation to restore your paint to a mirror-like, showroom-quality finish.", active: true },
      { title: "Ceramic Coating", description: "Long-lasting nano-ceramic protection that repels water, UV rays, and contaminants for years of pristine shine.", active: true },
      { title: "Headlight Restoration", description: "Restores clarity and improves night visibility, removing yellowing and oxidation from lenses.", active: true },
      { title: "Engine Cleaning", description: "Thorough engine bay degreasing and cleaning for a pristine engine that performs and looks its best.", active: true },
      { title: "Leather Protection", description: "Deep conditioning and protection treatment that restores suppleness, color, and durability to leather surfaces.", active: true },
      { title: "Stain Removal", description: "Advanced treatment to eliminate tough stains from upholstery, carpets, and surfaces — results guaranteed.", active: true },
      { title: "Full Detailing Package", description: "The complete treatment — interior deep clean, exterior wash, paint correction, and protection — all in one premium package.", active: true },
      { title: "Dash Cam Installation", description: "Professional installation of dash cameras for continuous recording, impact detection, and night vision. Wi-Fi and cloud options available.", active: true },
    ],
  },
  promotions: {
    eyebrow: "Limited Time Offers",
    heading: "Special Promotions",
    items: [
      { text: "20% off your first service", active: true },
      { text: "$15 off any full detailing package", active: true },
      { text: "Free interior wash on your first visit", active: true },
      { text: "Free consultation — no obligation", active: true },
    ],
  },
  mobileService: {
    heading1: "Mobile Service",
    heading2: "Available",
    body: "We come to you! Enjoy professional auto detailing at your home, workplace, or preferred location. We bring our own premium supplies and equipment.",
    cta: "Schedule Mobile Service",
  },
  whyUs: {
    eyebrow: "Why Choose Us",
    heading: "Driven by Quality",
    body: "We don't just wash cars; we restore and protect them. Our rigorous standards ensure every vehicle leaving our care looks better than the day it left the showroom.",
    cta: "Get an estimate",
    benefits: [
      "Premium detailing services",
      "Attention to every detail",
      "Mobile service available",
      "Professional results",
      "Interior and exterior care",
      "Quality products used",
      "Customer satisfaction focused",
    ],
  },
  gallery: {
    eyebrow: "Our Work",
    heading: "Before & After",
    body: "Our results speak for themselves. Browse through some of our recent premium auto detailing projects.",
  },
  testimonials: [],
  seo: {
    title: "Albert Auto Detailing | Professional Car Detailing in Norwalk CT",
    description: "Professional auto detailing in Norwalk, CT. Interior detailing, ceramic coating, paint correction, engine cleaning, headlight restoration and more. Serving Fairfield County, Connecticut.",
    keywords: "auto detailing Norwalk CT, car detailing Norwalk, ceramic coating, paint correction, interior detailing, exterior detailing, headlight restoration, detailing near me, premium detailing",
    gaId: "",
    gscCode: "",
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Got Questions?",
    items: [
      { q: "Do you offer personalized quotes?", a: "Yes! We offer free, no-obligation personalized quotes. Reach us via WhatsApp, phone, or our quote form and we'll tailor a package to your vehicle and needs." },
      { q: "How can I book an appointment?", a: "You can book through WhatsApp at 475-689-8301, call us directly, or fill out our online quote form. We'll confirm your appointment promptly." },
      { q: "Do you show prices online?", a: "We don't list fixed prices because every vehicle and service is unique. Contact us for a free personalized quote — no obligation whatsoever." },
      { q: "What services do you offer?", a: "We offer interior & exterior wash, paint correction, ceramic coating, headlight restoration, engine cleaning, leather protection, stain removal, and full detailing packages." },
      { q: "Where are you located?", a: "We are located in Norwalk, Connecticut 06851. We also offer mobile service throughout Norwalk, Stamford, Bridgeport, and surrounding CT areas." },
      { q: "Can I contact you through WhatsApp?", a: "Absolutely! WhatsApp is our preferred channel. Message or call us at 475-689-8301 and we'll respond as quickly as possible." },
    ],
  },
  contact: {
    eyebrow: "Get In Touch",
    heading: "Book Your Appointment",
    body: "Ready to give your vehicle the premium treatment it deserves? Contact us today to schedule your detailing service.",
    phone: "475-689-8301",
    email: "albertautodetailing2024@gmail.com",
    instagram: "albert_auto__detailing",
    whatsapp: "14756898301",
    facebook: "",
    tiktok: "",
    address: "Norwalk, Connecticut 06851",
    hours: "Mon–Sat: 8am–6pm",
    whatsappText: "Hi! I'd like to book a detailing service.",
    callLabel: "Call Now",
    emailLabel: "Send Email",
    instagramLabel: "Follow Us",
  },
  quoteForm: {
    eyebrow: "Request a Quote",
    heading: "Get Your Free Estimate",
    body: "Fill out the form and we'll get back to you with a personalized quote. No obligation, completely free.",
    submitLabel: "Send Request via WhatsApp",
  },
  location: {
    eyebrow: "Find Us",
    heading: "Our Location",
    address: "12 Jenny Jenks St, Norwalk, Connecticut 06851",
    hours: "Mon–Sat: 8am–6pm",
    areaNote: "We also offer mobile service throughout Norwalk, Stamford, Bridgeport, and surrounding CT areas.",
  },
  footer: {
    tagline: "Premium Detailing. Pristine Results.",
    sub: "Serving Norwalk, CT and surrounding areas.",
    rights: "All rights reserved.",
  },
  sections: {
    hero: true,
    about: true,
    services: true,
    promotions: true,
    mobileService: true,
    whyUs: true,
    gallery: true,
    testimonials: true,
    faq: true,
    contact: true,
    quoteForm: true,
    location: true,
  },
};

export type SiteContent = typeof defaultContent;
